org: duyhung
app: bku-project
service: bku-project-api
plugins:
  # - serverless-webpack
  - serverless-offline
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
functions:
  image_social_api:
    handler: src/index.graphqlHandler
    events:
      - http:
          path: /
          method: any
          cors: true
package:
  individually: true
  excludeDevDependencies: true
  # patterns:
  #   - '!node_modules/**'
  #   - 'node_modules/.prisma/**'
  #   - 'node_modules/apollo-server-lambda/**'
  #   - 'node_modules/graphql/**'
  #   - 'node_modules/dotenv/**'
custom:
  serverless-offline:
    httpPort: 4000
  # webpack:
  #   webpackConfig: 'webpack.config.js' # Name of webpack configuration file
  #   includeModules: false # Node modules configuration for packaging
  #   packager: 'npm' # Packager that will be used to package your external modules
  #   excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
